#!/bin/bash

if [ -x ${3}/usr/bin/cpp ] && [ ! -e ${3}/lib/cpp ];then
  if [ ! -d ${3}/lib ];then
    mkdir -p ${3}/lib
  fi;
  ln -s ../usr/bin/cpp ${3}/lib/cpp
fi;

if [ -x ${3}/usr/bin/gjar ] && [ ! -e ${3}/usr/bin/jar ];then
  ln -s gjar ${3}/usr/bin/jar
fi;

if [ -x ${3}/usr/bin/gcc ] && [ ! -e ${3}/usr/bin/cc ];then
  ln -s gcc ${3}/usr/bin/cc
fi;

#Use Target here not x86_64
#for gtool in `(cd ${3}/usr/bin/;ls  gnat*)`;do
#  ln -s  ${gtool} ${3}/usr/bin/x86_64-linux-gnu-${gtool}
#done
